# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'des.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from Application.settingsEva import SettingsEva

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(699, 542)
        MainWindow.setMinimumSize(QtCore.QSize(750, 542))
        MainWindow.setStyleSheet("background-color: rgb(65,105,225)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, 100, -1, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Button_History = QtWidgets.QPushButton(self.centralwidget)
        self.Button_History.setStyleSheet("color: white;border: none;font: 17px ;text-align:left;")
        self.Button_History.setObjectName("Button_History")
        self.verticalLayout.addWidget(self.Button_History)
        self.Button_Settings = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Settings.setStyleSheet("color: white;border: none;font: 17px ;text-align:left;")
        self.Button_Settings.setObjectName("Button_Settings")
        self.verticalLayout.addWidget(self.Button_Settings)
        self.settings_button_widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_button_widget.sizePolicy().hasHeightForWidth())
        self.settings_button_widget.setSizePolicy(sizePolicy)
        self.settings_button_widget.setObjectName("settings_button_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.settings_button_widget)
        self.verticalLayout_2.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Button_Settings_Micro = QtWidgets.QPushButton(self.settings_button_widget)
        self.Button_Settings_Micro.setEnabled(True)
        self.Button_Settings_Micro.setStyleSheet("color: white;border: none;font: 17px\n"
"                                                    ;text-align:left;\n"
"                                                ")
        self.Button_Settings_Micro.setObjectName("Button_Settings_Micro")
        self.verticalLayout_2.addWidget(self.Button_Settings_Micro)
        self.Button_Settings_Interface = QtWidgets.QPushButton(self.settings_button_widget)
        self.Button_Settings_Interface.setStyleSheet("color: white;border: none;font: 17px\n"
"                                                    ;text-align:left;\n"
"                                                ")
        self.Button_Settings_Interface.setObjectName("Button_Settings_Interface")
        self.verticalLayout_2.addWidget(self.Button_Settings_Interface)
        self.Button_Settings_Notify = QtWidgets.QPushButton(self.settings_button_widget)
        self.Button_Settings_Notify.setStyleSheet("color: white;border: none;font: 17px\n"
"                                                    ;text-align:left;\n"
"                                                ")
        self.Button_Settings_Notify.setObjectName("Button_Settings_Notify")
        self.verticalLayout_2.addWidget(self.Button_Settings_Notify)
        self.verticalLayout.addWidget(self.settings_button_widget)
        self.Button_Modules = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Modules.setStyleSheet("color: white;border: none;font: 17px ;text-align:left;")
        self.Button_Modules.setObjectName("Button_Modules")
        self.verticalLayout.addWidget(self.Button_Modules)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setStyleSheet("c")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.Button_About = QtWidgets.QPushButton(self.centralwidget)
        self.Button_About.setAutoFillBackground(False)
        self.Button_About.setStyleSheet("color: white;border: none;font: 17px ;text-align:left;")
        self.Button_About.setObjectName("Button_About")
        self.verticalLayout.addWidget(self.Button_About)
        self.exit_Button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_Button.setStyleSheet("color: white;border: none;font: 17px ;text-align:left;")
        self.exit_Button.setObjectName("exit_Button")
        self.verticalLayout.addWidget(self.exit_Button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("background-color: white;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.history_page = QtWidgets.QWidget()
        self.history_page.setObjectName("history_page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.history_page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ScrollArea_History = QtWidgets.QScrollArea(self.history_page)
        self.ScrollArea_History.setWidgetResizable(True)
        self.ScrollArea_History.setObjectName("ScrollArea_History")
        self.ListWidget_History = QtWidgets.QListWidget(self.ScrollArea_History)
        self.ListWidget_History.setObjectName("ListWidget_History")
        self.scrollAreaWidgetContents_8 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.scrollAreaWidgetContents_8.setObjectName("scrollAreaWidgetContents_8")
        self.ScrollArea_History.setWidget(self.scrollAreaWidgetContents_8)
        self.gridLayout_4.addWidget(self.ScrollArea_History, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.history_page)
        self.modules_page = QtWidgets.QWidget()
        self.modules_page.setObjectName("modules_page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.modules_page)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.ListWidget_ModuleCommands = QtWidgets.QListWidget(self.modules_page)
        self.ListWidget_ModuleCommands.setObjectName("ListWidget_ModuleCommands")
        self.gridLayout_7.addWidget(self.ListWidget_ModuleCommands, 1, 1, 1, 1)
        self.ListWidget_ModuleNames = QtWidgets.QListWidget(self.modules_page)
        self.ListWidget_ModuleNames.setObjectName("ListWidget_ModuleNames")
        self.gridLayout_7.addWidget(self.ListWidget_ModuleNames, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.modules_page)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.modules_page)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 0, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_7)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.ScrollArea_CommandInfo = QtWidgets.QScrollArea(self.modules_page)
        self.ScrollArea_CommandInfo.setWidgetResizable(True)
        self.ScrollArea_CommandInfo.setObjectName("ScrollArea_CommandInfo")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 542, 251))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_7)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.Label_CommandInfo = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.Label_CommandInfo.setText("")
        self.Label_CommandInfo.setObjectName("Label_CommandInfo")
        self.gridLayout_6.addWidget(self.Label_CommandInfo, 0, 0, 1, 1)
        self.ScrollArea_CommandInfo.setWidget(self.scrollAreaWidgetContents_7)
        self.gridLayout_5.addWidget(self.ScrollArea_CommandInfo, 1, 0, 1, 1)
        self.gridWidget_2 = QtWidgets.QWidget(self.modules_page)
        self.gridWidget_2.setObjectName("gridWidget_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridWidget_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_5.addWidget(self.gridWidget_2, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.modules_page)
        self.setting_micro_page = QtWidgets.QWidget()
        self.setting_micro_page.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.setting_micro_page.setObjectName("setting_micro_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.setting_micro_page)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(40, 0, 39, 40)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.ComboBox_Micro = QtWidgets.QFontComboBox(self.setting_micro_page)
        self.ComboBox_Micro.setStyleSheet("color: rgb(65,105,225);")
        self.ComboBox_Micro.setObjectName("ComboBox_Micro")
        self.gridLayout.addWidget(self.ComboBox_Micro, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.setting_micro_page)
        self.label.setStyleSheet("color: rgb(65,105,225);")
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.label_2 = QtWidgets.QLabel(self.setting_micro_page)
        self.label_2.setStyleSheet("color: rgb(65,105,225);")
        self.label_2.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.Slider_Micro_Volume = QtWidgets.QSlider(self.setting_micro_page)
        self.Slider_Micro_Volume.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Micro_Volume.setObjectName("Slider_Micro_Volume")
        self.gridLayout.addWidget(self.Slider_Micro_Volume, 1, 1, 1, 1)


        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Button_Check_Micro = QtWidgets.QPushButton(self.setting_micro_page)
        self.Button_Check_Micro.setMinimumSize(QtCore.QSize(0, 40))
        self.Button_Check_Micro.setBaseSize(QtCore.QSize(0, 100))
        self.Button_Check_Micro.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Button_Check_Micro.setFlat(False)
        self.Button_Check_Micro.setObjectName("Button_Check_Micro")
        self.horizontalLayout_2.addWidget(self.Button_Check_Micro)
        self.micro_check_bar = QtWidgets.QProgressBar(self.setting_micro_page)
        self.micro_check_bar.setProperty("value", 24)
        self.micro_check_bar.setFormat("")
        self.micro_check_bar.setObjectName("micro_check_bar")
        self.horizontalLayout_2.addWidget(self.micro_check_bar)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.setting_micro_page)
        self.label_4.setStyleSheet("color: rgb(65,105,225);")
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.setting_micro_page)
        self.label_3.setStyleSheet("color: rgb(65,105,225);")
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.CheckBox_HotKey = QtWidgets.QCheckBox(self.setting_micro_page)
        self.CheckBox_HotKey.setObjectName("CheckBox_HotKey")
        self.verticalLayout_3.addWidget(self.CheckBox_HotKey)
        self.CheckBox_KeyWork = QtWidgets.QCheckBox(self.setting_micro_page)
        self.CheckBox_KeyWork.setObjectName("CheckBox_KeyWork")
        self.verticalLayout_3.addWidget(self.CheckBox_KeyWork)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.HotKey_Choosen = QtWidgets.QKeySequenceEdit(self.setting_micro_page)
        self.HotKey_Choosen.setObjectName("HotKey_Choosen")
        self.gridLayout_2.addWidget(self.HotKey_Choosen, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.label_tws = QtWidgets.QLabel(self.setting_micro_page)
        self.label_tws.setStyleSheet("color: rgb(65,105,225);")
        self.label_tws.setAlignment(QtCore.Qt.AlignBottom)
        self.label_tws.setObjectName("label_tws")
        self.horizontalLayout_3.addWidget(self.label_tws)

        self.Slider_Micro_Kws_Threshold = QtWidgets.QSlider(self.setting_micro_page)
        self.Slider_Micro_Kws_Threshold.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Micro_Kws_Threshold.setMaximum(50)
        self.Slider_Micro_Kws_Threshold.setSingleStep(5)
        self.Slider_Micro_Kws_Threshold.setObjectName("Slider_Micro_Kws_Threshold")
        self.horizontalLayout_3.addWidget(self.Slider_Micro_Kws_Threshold)

        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.stackedWidget.addWidget(self.setting_micro_page)
        self.settings_notification_page = QtWidgets.QWidget()
        self.settings_notification_page.setObjectName("settings_notification_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.settings_notification_page)
        self.gridLayout_3.setContentsMargins(40, -1, 40, 200)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.settings_notification_page)
        self.label_5.setStyleSheet("color: rgb(65,105,225);")
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.ToggleSlider_SoundNotify = QtWidgets.QSlider(self.settings_notification_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToggleSlider_SoundNotify.sizePolicy().hasHeightForWidth())
        self.ToggleSlider_SoundNotify.setSizePolicy(sizePolicy)
        self.ToggleSlider_SoundNotify.setMaximum(1)
        self.ToggleSlider_SoundNotify.setOrientation(QtCore.Qt.Horizontal)
        self.ToggleSlider_SoundNotify.setObjectName("ToggleSlider_SoundNotify")
        self.gridLayout_3.addWidget(self.ToggleSlider_SoundNotify, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.settings_notification_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setStyleSheet("color: rgb(65,105,225);")
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.ToggleSlider_TextNotify = QtWidgets.QSlider(self.settings_notification_page)
        self.ToggleSlider_TextNotify.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToggleSlider_TextNotify.sizePolicy().hasHeightForWidth())
        self.ToggleSlider_TextNotify.setSizePolicy(sizePolicy)
        self.ToggleSlider_TextNotify.setStyleSheet("border-radius: 25px;")
        self.ToggleSlider_TextNotify.setMaximum(1)
        self.ToggleSlider_TextNotify.setOrientation(QtCore.Qt.Horizontal)
        self.ToggleSlider_TextNotify.setObjectName("ToggleSlider_TextNotify")
        self.gridLayout_3.addWidget(self.ToggleSlider_TextNotify, 0, 1, 1, 1)

        self.stackedWidget.addWidget(self.settings_notification_page)
        self.settings_interface_page = QtWidgets.QWidget()
        self.settings_interface_page.setObjectName("settings_interface_page")
        self.settings_interface_page_layout = QtWidgets.QVBoxLayout(self.settings_interface_page)
        self.settings_interface_page_layout.setSpacing(20)
        self.settings_interface_page_layout.setObjectName("settings_interface_page_layout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.settings_interface_page_layout.addItem(spacerItem1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, -1, -1, 60)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.settings_interface_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.horizontalSlider = QtWidgets.QSlider(self.settings_interface_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_6.addWidget(self.horizontalSlider)
        self.settings_interface_page_layout.addLayout(self.verticalLayout_6)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.settings_interface_page_layout.addItem(spacerItem2)
        self.stackedWidget.addWidget(self.settings_interface_page)
        self.about_app = QtWidgets.QWidget()
        self.about_app.setObjectName("about_app")
        self.settings_aboutapp_page_layout = QtWidgets.QVBoxLayout(self.about_app)
        self.settings_aboutapp_page_layout.setObjectName("settings_aboutapp_page_layout")
        self.label_8 = QtWidgets.QLabel(self.about_app)
        self.label_8.setObjectName("label_8")
        self.settings_aboutapp_page_layout.addWidget(self.label_8)
        self.stackedWidget.addWidget(self.about_app)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Eva"))
        self.Button_History.setText(_translate("MainWindow", "История"))
        self.Button_Settings.setText(_translate("MainWindow", "Настройки"))
        self.Button_Settings_Micro.setText(_translate("MainWindow", "Микрофон"))
        self.Button_Settings_Interface.setText(_translate("MainWindow", "Интерфейс"))
        self.Button_Settings_Notify.setText(_translate("MainWindow", "Уведомления"))
        self.Button_Modules.setText(_translate("MainWindow", "Модули"))
        self.Button_About.setText(_translate("MainWindow", "О приложении"))
        self.exit_Button.setText(_translate("MainWindow", "Выход"))
        self.label_11.setText(_translate("MainWindow", "Команда"))
        self.label_10.setText(_translate("MainWindow", "Модуль"))
        self.label.setText(_translate("MainWindow", "Выберите микрофон"))
        self.label_2.setText(_translate("MainWindow", "Громкость микрофона"))
        self.label_tws.setText(_translate("MainWindow", "Порог распознавания: 1e-"))
        self.Button_Check_Micro.setText(_translate("MainWindow", "Проверка микрофона"))
        self.label_4.setText(_translate("MainWindow", "Горячая клавиша"))
        self.label_3.setText(_translate("MainWindow", "Режим работы"))
        self.CheckBox_HotKey.setText(_translate("MainWindow", "Активация по горячей клавише"))
        self.CheckBox_KeyWork.setText(_translate("MainWindow", "Активация по ключевому слову"))
        self.HotKey_Choosen.setKeySequence(_translate("MainWindow", "F1"))
        self.label_5.setText(_translate("MainWindow", "Включить вывод текста на экран"))
        self.label_6.setText(_translate("MainWindow", "Включить звуковое оповещение"))
        self.label_7.setText(_translate("MainWindow", "Размер шрифта"))
        self.label_8.setText(_translate("MainWindow", "Здесь может быть ваша реклама. (8-800-555-35-35)"))
