# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'des.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(699, 542)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.history_page = QtWidgets.QWidget()
        self.history_page.setObjectName("history_page")
        self.stackedWidget.addWidget(self.history_page)
        self.modules_page = QtWidgets.QWidget()
        self.modules_page.setObjectName("modules_page")
        self.stackedWidget.addWidget(self.modules_page)
        self.setting_micro_page = QtWidgets.QWidget()
        self.setting_micro_page.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.setting_micro_page.setObjectName("setting_micro_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.setting_micro_page)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(40, 0, 39, 40)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Slider_Micro_Volume = QtWidgets.QSlider(self.setting_micro_page)
        self.Slider_Micro_Volume.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Micro_Volume.setObjectName("Slider_Micro_Volume")
        self.gridLayout.addWidget(self.Slider_Micro_Volume, 1, 1, 1, 1)
        self.ComboBox_Micro = QtWidgets.QFontComboBox(self.setting_micro_page)
        self.ComboBox_Micro.setObjectName("ComboBox_Micro")
        self.gridLayout.addWidget(self.ComboBox_Micro, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.setting_micro_page)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.setting_micro_page)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Button_Check_Micro = QtWidgets.QPushButton(self.setting_micro_page)
        self.Button_Check_Micro.setMinimumSize(QtCore.QSize(0, 40))
        self.Button_Check_Micro.setBaseSize(QtCore.QSize(0, 100))
        self.Button_Check_Micro.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Button_Check_Micro.setFlat(False)
        self.Button_Check_Micro.setObjectName("Button_Check_Micro")
        self.horizontalLayout_2.addWidget(self.Button_Check_Micro)
        self.micro_check_bar = QtWidgets.QProgressBar(self.setting_micro_page)
        self.micro_check_bar.setProperty("value", 24)
        self.micro_check_bar.setFormat("")
        self.micro_check_bar.setObjectName("micro_check_bar")
        self.horizontalLayout_2.addWidget(self.micro_check_bar)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.setting_micro_page)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.setting_micro_page)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.CheckBox_HotKey = QtWidgets.QCheckBox(self.setting_micro_page)
        self.CheckBox_HotKey.setObjectName("CheckBox_HotKey")
        self.verticalLayout_3.addWidget(self.CheckBox_HotKey)
        self.CheckBox_KeyWork = QtWidgets.QCheckBox(self.setting_micro_page)
        self.CheckBox_KeyWork.setObjectName("CheckBox_KeyWork")
        self.verticalLayout_3.addWidget(self.CheckBox_KeyWork)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.HotKey_Choosen = QtWidgets.QKeySequenceEdit(self.setting_micro_page)
        self.HotKey_Choosen.setObjectName("HotKey_Choosen")
        self.gridLayout_2.addWidget(self.HotKey_Choosen, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.stackedWidget.addWidget(self.setting_micro_page)
        self.settings_notification_page = QtWidgets.QWidget()
        self.settings_notification_page.setObjectName("settings_notification_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.settings_notification_page)
        self.gridLayout_3.setContentsMargins(40, -1, 40, 200)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.settings_notification_page)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.settings_notification_page)
        self.horizontalSlider_2.setMaximum(1)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.gridLayout_3.addWidget(self.horizontalSlider_2, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.settings_notification_page)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.settings_notification_page)
        self.horizontalSlider.setMaximum(1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_3.addWidget(self.horizontalSlider, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.settings_notification_page)
        self.settings_interface_page = QtWidgets.QWidget()
        self.settings_interface_page.setObjectName("settings_interface_page")
        self.stackedWidget.addWidget(self.settings_interface_page)
        self.about_app = QtWidgets.QWidget()
        self.about_app.setObjectName("about_app")
        self.label_7 = QtWidgets.QLabel(self.about_app)
        self.label_7.setGeometry(QtCore.QRect(180, 220, 67, 17))
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.about_app)
        self.gridLayout_4.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, 100, -1, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Button_History = QtWidgets.QPushButton(self.centralwidget)
        self.Button_History.setObjectName("Button_History")
        self.verticalLayout.addWidget(self.Button_History)
        self.Button_Settings = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Settings.setObjectName("Button_Settings")
        self.verticalLayout.addWidget(self.Button_Settings)
        self.settings_button_widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_button_widget.sizePolicy().hasHeightForWidth())
        self.settings_button_widget.setSizePolicy(sizePolicy)
        self.settings_button_widget.setObjectName("settings_button_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.settings_button_widget)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Button_Settings_Micro = QtWidgets.QPushButton(self.settings_button_widget)
        self.Button_Settings_Micro.setEnabled(True)
        self.Button_Settings_Micro.setObjectName("Button_Settings_Micro")
        self.verticalLayout_2.addWidget(self.Button_Settings_Micro)
        self.Button_Settings_Interface = QtWidgets.QPushButton(self.settings_button_widget)
        self.Button_Settings_Interface.setObjectName("Button_Settings_Interface")
        self.verticalLayout_2.addWidget(self.Button_Settings_Interface)
        self.Button_Settings_Notify = QtWidgets.QPushButton(self.settings_button_widget)
        self.Button_Settings_Notify.setObjectName("Button_Settings_Notify")
        self.verticalLayout_2.addWidget(self.Button_Settings_Notify)
        self.verticalLayout.addWidget(self.settings_button_widget)
        self.Button_Modules = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Modules.setObjectName("Button_Modules")
        self.verticalLayout.addWidget(self.Button_Modules)
        self.Button_About = QtWidgets.QPushButton(self.centralwidget)
        self.Button_About.setObjectName("Button_About")
        self.verticalLayout.addWidget(self.Button_About)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Eva"))
        self.label.setText(_translate("MainWindow", "Выберите микрофон"))
        self.label_2.setText(_translate("MainWindow", "Громкость микрофона"))
        self.Button_Check_Micro.setText(_translate("MainWindow", "Проверка микрофона"))
        self.label_4.setText(_translate("MainWindow", "Горячая клавиша"))
        self.label_3.setText(_translate("MainWindow", "Режим работы"))
        self.CheckBox_HotKey.setText(_translate("MainWindow", "Активация по горячей клавише"))
        self.CheckBox_KeyWork.setText(_translate("MainWindow", "Активация по ключевому слову"))
        self.HotKey_Choosen.setKeySequence(_translate("MainWindow", "F1"))
        self.label_5.setText(_translate("MainWindow", "Включить вывод текста на экран"))
        self.label_6.setText(_translate("MainWindow", "Включить звуковое оповещение "))
        self.label_7.setText(_translate("MainWindow", "Ти пидор"))
        self.Button_History.setText(_translate("MainWindow", "История"))
        self.Button_Settings.setText(_translate("MainWindow", "Настройки"))
        self.Button_Settings_Micro.setText(_translate("MainWindow", "Микрофон"))
        self.Button_Settings_Interface.setText(_translate("MainWindow", "Интерфейс"))
        self.Button_Settings_Notify.setText(_translate("MainWindow", "Уведомления"))
        self.Button_Modules.setText(_translate("MainWindow", "Модули"))
        self.Button_About.setText(_translate("MainWindow", "О приложении"))


